config:
  replant_effect:
    enable: true
    effect: BONE_MEAL_USE #https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  guardian_effect:
    enable: true
    particle: ELECTRIC_SPARK
    count: 1
regions:
