name: FarmRegion
version: '${project.version}'
main: rama.farmRegion.FarmRegion
api-version: 1.14
authors: [ ImRama ]
description: Create automatic farm regions for your players.
load: POSTWORLD
softdepend:
  - Multiverse-Core
  - WorldGuard
  - UltraRegions
commands:
  fr:
    aliases: ["farmregion"]
