name: FarmRegion
version: '${project.version}'
main: rama.farmRegion.FarmRegion
api-version: 1.14
authors: [ ImRama ]
description: Create automatic farm regions for your players.
load: POSTWORLD
softdepend: [WorldGuard, UltraRegions, Multiverse-Core]
commands:
  fr:
    aliases: ["farmregion"]
